### ISSUE TITLE
Add Mentor additional profile fields [GEM-100]

### ISSUE THREAD

**Issue by TrevorOctober** [praekelt/mentorship#64]
Add support for editing mentor and mentee profile fields.

- #67 (mentor profile fields)

**Comment by hodgestar** [comment]
Things still needed after #67 lands:

**Add GET detail route for retrieving the PNG**:

  - [ ] Add tests for the route.
  - [ ] Check that the route returns a 200 response.
  - [ ] Check that the route returns the correct content type.
  - [ ] Check that the route requires a login.
  - [ ] Check that the route returns a 404 for mentors that don't exist.
  - [ ] Check that the route returns a 404 if the profile picture does not exist.

**For existing detail PUT route for updating the PNG**:

  - [ ] Check that the 201 response returns the correct URL for retrieving the profile picture in the response body.
  - [ ] Change the image field to store images in a custom folder (i.e. not `/media/` which is usually exposed via nginx without authentication).
  - [ ] Check that a descriptive error message is returned when no image file is sent.
  - [ ] Check that a descriptive error message is returned when the content is not a PNG (i.e. does not have type image/png).

**Mentee profile fields**

These still need to be added.

**Comment by KaitCrawford** [comment]
Just a note, mentee fields are no longer required. They were removed from the details of the ticket but the ticket name was not changed and so the name of this issue hasn't been changed

**Comment by hodgestar** [comment]
Once #81 lands, this is hopefully done.
